### ISSUE TITLE
Install fails in case of using Score-P dev version.

### ISSUE THREAD

**Issue by harryherold** [score-p/scorep_binding_python#60]
I am using a Score-P development version and I tried to install the Score-P python package in a virtual env. I get the following message:
```sh
$ pip install scorep
Collecting scorep
  Using cached scorep-3.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/cherold/workspace/python/resnet50/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-466ptxwo/scorep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-466ptxwo/scorep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-466ptxwo/scorep/pip-egg-info
         cwd: /tmp/pip-install-466ptxwo/scorep/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-466ptxwo/scorep/setup.py", line 4, in <module>
        if scorep.helper.get_scorep_version() < 5.0:
      File "/tmp/pip-install-466ptxwo/scorep/scorep/helper.py", line 43, in get_scorep_version
        version = float(std_out.lstrip("Score-P"))
    ValueError: could not convert string to float: ' 7.0-dev\n'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
It seems the string parsing is not considering all cases of a Score-P version.

**Comment by AndreasGocht** [comment]
Fixed.
